"""
Generates a VoiceLedger income proof PDF.
Install: pip install fpdf2
"""
from fpdf import FPDF
from app.models.entry import LedgerEntry
from app.models.user import TelegramUser
import tempfile, os
from datetime import datetime

def generate_proof_pdf(user: TelegramUser, entries: list[LedgerEntry]) -> str:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "VoiceLedger — Income Proof", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%d %b %Y, %H:%M UTC')}", ln=True, align="C")
    pdf.cell(0, 6, f"Worker: {user.full_name or 'Unknown'}  |  Telegram ID: {user.id}", ln=True, align="C")
    pdf.ln(8)

    # Divider
    pdf.set_draw_color(200, 200, 200)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(6)

    # Entries
    pdf.set_text_color(0, 0, 0)
    for i, e in enumerate(entries, 1):
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, f"Entry #{i} — {e.employer or 'Unknown employer'}", ln=True)
        pdf.set_font("Helvetica", "", 10)

        fields = [
            ("Role",         e.role),
            ("Wage",         e.wage),
            ("Start Date",   e.start_date),
            ("End Date",     e.end_date),
            ("Hours/Week",   str(e.hours_per_week) if e.hours_per_week else None),
            ("Notes",        e.notes),
            ("Recorded on",  e.created_at.strftime("%d %b %Y") if e.created_at else None),
        ]
        for label, value in fields:
            if value:
                pdf.set_text_color(100, 100, 100)
                pdf.cell(40, 6, f"{label}:", border=0)
                pdf.set_text_color(0, 0, 0)
                pdf.multi_cell(0, 6, value)

        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(140, 140, 140)
        pdf.multi_cell(0, 5, f'Transcript: "{e.raw_transcript}"')
        pdf.ln(4)
        pdf.set_draw_color(230, 230, 230)
        pdf.line(20, pdf.get_y(), 190, pdf.get_y())
        pdf.ln(4)

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(160, 160, 160)
    pdf.cell(0, 6, "This document was generated by VoiceLedger. Records are self-declared and voice-verified.", align="C")

    path = tempfile.mktemp(suffix=".pdf")
    pdf.output(path)
    return path